import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

interface TripStop {
  cityName: string
  country?: string
  startDate: string | Date
  endDate: string | Date
  activities: { name: string; category?: string; cost?: number }[]
}

interface TripData {
  title: string
  description?: string
  startDate: string | Date
  endDate: string | Date
  totalBudget?: number
  currency?: string
  stops: TripStop[]
  expenses?: { category: string; description: string; amount: number }[]
}

export function exportTripToPDF(trip: TripData) {
  const doc = new jsPDF()
  const currency = trip.currency || 'USD'
  const formatDate = (d: string | Date) =>
    new Date(d).toLocaleDateString('en-US', { day: 'numeric', month: 'short', year: 'numeric' })
  const formatMoney = (n: number) =>
    new Intl.NumberFormat('en-US', { style: 'currency', currency }).format(n)

  // ── Header ──
  doc.setFillColor(7, 11, 20)
  doc.rect(0, 0, 210, 45, 'F')

  doc.setTextColor(255, 107, 107)
  doc.setFontSize(24)
  doc.setFont('helvetica', 'bold')
  doc.text('TRAVELOOP', 14, 18)

  doc.setTextColor(176, 190, 197)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('Your Personalized Travel Plan', 14, 26)

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text(trip.title, 14, 38)

  // ── Trip Info ──
  doc.setTextColor(50, 50, 50)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  let y = 55

  if (trip.description) {
    doc.setTextColor(100, 100, 100)
    doc.text(trip.description, 14, y, { maxWidth: 180 })
    y += 12
  }

  // Info boxes
  const infos = [
    ['📅 Start Date', formatDate(trip.startDate)],
    ['📅 End Date', formatDate(trip.endDate)],
    ['🏙️ Destinations', String(trip.stops.length)],
    ...(trip.totalBudget ? [['💰 Budget', formatMoney(trip.totalBudget)]] : []),
  ]

  autoTable(doc, {
    startY: y,
    body: infos.map(([label, value]) => [label, value]),
    theme: 'grid',
    styles: { fontSize: 9, cellPadding: 4 },
    columnStyles: {
      0: { fontStyle: 'bold', fillColor: [245, 245, 250], cellWidth: 60 },
      1: { cellWidth: 120 },
    },
    margin: { left: 14, right: 14 },
  })

  y = (doc as any).lastAutoTable.finalY + 10

  // ── Itinerary ──
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(255, 107, 107)
  doc.text('ITINERARY', 14, y)
  y += 6

  trip.stops.forEach((stop, idx) => {
    if (y > 240) { doc.addPage(); y = 20 }

    doc.setFillColor(13, 22, 40)
    doc.setDrawColor(255, 107, 107)
    doc.roundedRect(14, y, 182, 10, 2, 2, 'FD')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.text(
      `Stop ${idx + 1}: ${stop.cityName}${stop.country ? ', ' + stop.country : ''}   ${formatDate(stop.startDate)} → ${formatDate(stop.endDate)}`,
      18,
      y + 7
    )
    y += 14

    if (stop.activities.length > 0) {
      autoTable(doc, {
        startY: y,
        head: [['Activity', 'Category', 'Cost']],
        body: stop.activities.map(a => [
          a.name,
          a.category || '—',
          a.cost ? formatMoney(a.cost) : '—',
        ]),
        theme: 'striped',
        styles: { fontSize: 8, cellPadding: 3 },
        headStyles: { fillColor: [0, 229, 204], textColor: [0, 0, 0] },
        margin: { left: 14, right: 14 },
      })
      y = (doc as any).lastAutoTable.finalY + 6
    } else {
      doc.setTextColor(150, 150, 150)
      doc.setFontSize(8)
      doc.text('No activities added yet', 18, y)
      y += 8
    }
  })

  // ── Expenses ──
  if (trip.expenses && trip.expenses.length > 0) {
    if (y > 220) { doc.addPage(); y = 20 }

    doc.setFontSize(13)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(255, 184, 48)
    doc.text('EXPENSES', 14, y)
    y += 6

    const totalSpent = trip.expenses.reduce((sum, e) => sum + e.amount, 0)

    autoTable(doc, {
      startY: y,
      head: [['Category', 'Description', 'Amount']],
      body: [
        ...trip.expenses.map(e => [e.category, e.description, formatMoney(e.amount)]),
        ['', 'TOTAL SPENT', formatMoney(totalSpent)],
      ],
      theme: 'striped',
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [255, 184, 48], textColor: [0, 0, 0] },
      foot: [[`Budget: ${trip.totalBudget ? formatMoney(trip.totalBudget) : 'N/A'}`, '', `Remaining: ${trip.totalBudget ? formatMoney(trip.totalBudget - totalSpent) : 'N/A'}`]],
      footStyles: { fontStyle: 'bold', fillColor: [240, 244, 255] },
      margin: { left: 14, right: 14 },
    })
  }

  // ── Footer ──
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text(
      `Generated by Traveloop • ${new Date().toLocaleDateString()}  |  Page ${i} of ${pageCount}`,
      14,
      doc.internal.pageSize.height - 8
    )
  }

  doc.save(`${trip.title.replace(/\s+/g, '_')}_traveloop.pdf`)
}
